stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:latest
  stage: build
  script:
    - mvn clean package

maven-test:
  image: maven:latest
  stage: test
  script:
    - mvn clean test

deployment:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$APP_NAME --api_key=$API_KEY



